camera_left:
  ros__parameters:
    device_path: "/dev/video0"
    frame_id: "camera_left"
    topic_name: "camera_left/image_raw"
    width: 1280
    height: 720
    fps: 30

camera_mid:
  ros__parameters:
    device_path: "/dev/video2"
    frame_id: "camera_mid"
    topic_name: "camera_mid/image_raw"
    width: 1280
    height: 720
    fps: 30

camera_right:
  ros__parameters:
    device_path: "/dev/video4"
    frame_id: "camera_right"
    topic_name: "camera_right/image_raw"
    width: 1280
    height: 720
    fps: 30 