camera1:
  ros__parameters:
    device_path: "/dev/video0"
    frame_id: "camera1"
    topic_name: "camera1/image_raw"
    width: 1920
    height: 1080
    fps: 30

camera2:
  ros__parameters:
    device_path: "/dev/video1"
    frame_id: "camera2"
    topic_name: "camera2/image_raw"
    width: 1920
    height: 1080
    fps: 30

camera3:
  ros__parameters:
    device_path: "/dev/video2"
    frame_id: "camera3"
    topic_name: "camera3/image_raw"
    width: 1920
    height: 1080
    fps: 30 